################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
SAG_SRCS += \

SAG_FILE += \

GPROF_OUT := 
PWR_OUT := 
SIZE_OUTPUTS := 
READELF_OUTPUTS := 
EXECUTABLES := 
OBJDUMP_OUTPUTS := 
OBJS := 
SYMBOL_OUTPUTS := 
S_UPPER_DEPS := 
GCOV_OUT := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
3rd-party/freertos-V5 \
3rd-party/freertos-V5/portable/GCC/RISC-V \
3rd-party/freertos-V5/portable/MemMang \
application/app \
application/audio \
application/keyboard \
application/print \
application/usbstd \
boot/B91 \
common \
common/usb_dbg \
drivers/B91 \
drivers/B91/ext_driver \
drivers/B91/flash \
proj/common \
vendor/UI/components \
vendor/UI/screens \
vendor/UI \
vendor/common \
vendor/common/chip_adapt_layer \
vendor/common/mi_api \
vendor/common/mi_api/libs \
vendor/common/mi_api/libs/third_party/micro-ecc \
vendor/common/mi_api/mi_vendor \
vendor/common/mi_api/mijia_ble_api \
vendor/common/nl_api \
vendor/lvgl/demos/benchmark/assets \
vendor/lvgl/demos/benchmark \
vendor/lvgl/demos/flex_layout \
vendor/lvgl/demos/keypad_encoder \
vendor/lvgl/demos \
vendor/lvgl/demos/multilang/assets/avatars \
vendor/lvgl/demos/multilang/assets/emojis \
vendor/lvgl/demos/multilang/assets/fonts \
vendor/lvgl/demos/multilang/assets \
vendor/lvgl/demos/multilang \
vendor/lvgl/demos/music/assets \
vendor/lvgl/demos/music \
vendor/lvgl/demos/render/assets \
vendor/lvgl/demos/render \
vendor/lvgl/demos/scroll \
vendor/lvgl/demos/stress \
vendor/lvgl/demos/transform/assets \
vendor/lvgl/demos/transform \
vendor/lvgl/demos/vector_graphic/assets \
vendor/lvgl/demos/vector_graphic \
vendor/lvgl/demos/widgets/assets \
vendor/lvgl/demos/widgets \
vendor/lvgl/env_support/pikascript \
vendor/lvgl/env_support/rt-thread \
vendor/lvgl/env_support/rt-thread/squareline \
vendor/lvgl/examples/anim \
vendor/lvgl/examples/assets \
vendor/lvgl/examples/assets/emoji \
vendor/lvgl/examples/event \
vendor/lvgl/examples/get_started \
vendor/lvgl/examples/layouts/flex \
vendor/lvgl/examples/layouts/grid \
vendor/lvgl/examples/libs/barcode \
vendor/lvgl/examples/libs/bmp \
vendor/lvgl/examples/libs/ffmpeg \
vendor/lvgl/examples/libs/freetype \
vendor/lvgl/examples/libs/gif \
vendor/lvgl/examples/libs/libjpeg_turbo \
vendor/lvgl/examples/libs/libpng \
vendor/lvgl/examples/libs/lodepng \
vendor/lvgl/examples/libs/qrcode \
vendor/lvgl/examples/libs/rlottie \
vendor/lvgl/examples/libs/tiny_ttf \
vendor/lvgl/examples/libs/tjpgd \
vendor/lvgl/examples/others/file_explorer \
vendor/lvgl/examples/others/fragment \
vendor/lvgl/examples/others/gridnav \
vendor/lvgl/examples/others/ime \
vendor/lvgl/examples/others/imgfont \
vendor/lvgl/examples/others/monkey \
vendor/lvgl/examples/others/observer \
vendor/lvgl/examples/others/snapshot \
vendor/lvgl/examples/porting \
vendor/lvgl/examples/scroll \
vendor/lvgl/examples/styles \
vendor/lvgl/examples/widgets/animimg \
vendor/lvgl/examples/widgets/arc \
vendor/lvgl/examples/widgets/bar \
vendor/lvgl/examples/widgets/button \
vendor/lvgl/examples/widgets/buttonmatrix \
vendor/lvgl/examples/widgets/calendar \
vendor/lvgl/examples/widgets/canvas \
vendor/lvgl/examples/widgets/chart \
vendor/lvgl/examples/widgets/checkbox \
vendor/lvgl/examples/widgets/dropdown \
vendor/lvgl/examples/widgets/image \
vendor/lvgl/examples/widgets/imagebutton \
vendor/lvgl/examples/widgets/keyboard \
vendor/lvgl/examples/widgets/label \
vendor/lvgl/examples/widgets/led \
vendor/lvgl/examples/widgets/line \
vendor/lvgl/examples/widgets/list \
vendor/lvgl/examples/widgets/menu \
vendor/lvgl/examples/widgets/msgbox \
vendor/lvgl/examples/widgets/obj \
vendor/lvgl/examples/widgets/roller \
vendor/lvgl/examples/widgets/scale \
vendor/lvgl/examples/widgets/slider \
vendor/lvgl/examples/widgets/span \
vendor/lvgl/examples/widgets/spinbox \
vendor/lvgl/examples/widgets/spinner \
vendor/lvgl/examples/widgets/switch \
vendor/lvgl/examples/widgets/table \
vendor/lvgl/examples/widgets/tabview \
vendor/lvgl/examples/widgets/textarea \
vendor/lvgl/examples/widgets/tileview \
vendor/lvgl/examples/widgets/win \
vendor/lvgl/src/core \
vendor/lvgl/src/display \
vendor/lvgl/src/draw \
vendor/lvgl/src/draw/nxp/pxp \
vendor/lvgl/src/draw/nxp/vglite \
vendor/lvgl/src/draw/renesas/dave2d \
vendor/lvgl/src/draw/sdl \
vendor/lvgl/src/draw/sw/blend/helium \
vendor/lvgl/src/draw/sw/blend \
vendor/lvgl/src/draw/sw/blend/neon \
vendor/lvgl/src/draw/sw \
vendor/lvgl/src/draw/vg_lite \
vendor/lvgl/src/drivers/display/drm \
vendor/lvgl/src/drivers/display/fb \
vendor/lvgl/src/drivers/display/ili9341 \
vendor/lvgl/src/drivers/display/lcd \
vendor/lvgl/src/drivers/display/st7735 \
vendor/lvgl/src/drivers/display/st7789 \
vendor/lvgl/src/drivers/display/st7796 \
vendor/lvgl/src/drivers/evdev \
vendor/lvgl/src/drivers/libinput \
vendor/lvgl/src/drivers/nuttx \
vendor/lvgl/src/drivers/sdl \
vendor/lvgl/src/drivers/windows \
vendor/lvgl/src/drivers/x11 \
vendor/lvgl/src/font \
vendor/lvgl/src/indev \
vendor/lvgl/src/layouts/flex \
vendor/lvgl/src/layouts/grid \
vendor/lvgl/src/layouts \
vendor/lvgl/src/libs/barcode \
vendor/lvgl/src/libs/bin_decoder \
vendor/lvgl/src/libs/bmp \
vendor/lvgl/src/libs/ffmpeg \
vendor/lvgl/src/libs/freetype \
vendor/lvgl/src/libs/fsdrv \
vendor/lvgl/src/libs/gif \
vendor/lvgl/src/libs/libjpeg_turbo \
vendor/lvgl/src/libs/libpng \
vendor/lvgl/src/libs/lodepng \
vendor/lvgl/src/libs/lz4 \
vendor/lvgl/src/libs/qrcode \
vendor/lvgl/src/libs/rle \
vendor/lvgl/src/libs/rlottie \
vendor/lvgl/src/libs/tiny_ttf \
vendor/lvgl/src/libs/tjpgd \
vendor/lvgl/src \
vendor/lvgl/src/misc/cache \
vendor/lvgl/src/misc \
vendor/lvgl/src/osal \
vendor/lvgl/src/others/file_explorer \
vendor/lvgl/src/others/fragment \
vendor/lvgl/src/others/gridnav \
vendor/lvgl/src/others/ime \
vendor/lvgl/src/others/imgfont \
vendor/lvgl/src/others/monkey \
vendor/lvgl/src/others/observer \
vendor/lvgl/src/others/snapshot \
vendor/lvgl/src/others/sysmon \
vendor/lvgl/src/others/vg_lite_tvg \
vendor/lvgl/src/stdlib/builtin \
vendor/lvgl/src/stdlib/clib \
vendor/lvgl/src/stdlib \
vendor/lvgl/src/stdlib/micropython \
vendor/lvgl/src/stdlib/rtthread \
vendor/lvgl/src/themes/default \
vendor/lvgl/src/themes \
vendor/lvgl/src/themes/mono \
vendor/lvgl/src/themes/simple \
vendor/lvgl/src/tick \
vendor/lvgl/src/widgets/animimage \
vendor/lvgl/src/widgets/arc \
vendor/lvgl/src/widgets/bar \
vendor/lvgl/src/widgets/button \
vendor/lvgl/src/widgets/buttonmatrix \
vendor/lvgl/src/widgets/calendar \
vendor/lvgl/src/widgets/canvas \
vendor/lvgl/src/widgets/chart \
vendor/lvgl/src/widgets/checkbox \
vendor/lvgl/src/widgets/dropdown \
vendor/lvgl/src/widgets/image \
vendor/lvgl/src/widgets/imagebutton \
vendor/lvgl/src/widgets/keyboard \
vendor/lvgl/src/widgets/label \
vendor/lvgl/src/widgets/led \
vendor/lvgl/src/widgets/line \
vendor/lvgl/src/widgets/list \
vendor/lvgl/src/widgets/menu \
vendor/lvgl/src/widgets/msgbox \
vendor/lvgl/src/widgets/objx_templ \
vendor/lvgl/src/widgets/roller \
vendor/lvgl/src/widgets/scale \
vendor/lvgl/src/widgets/slider \
vendor/lvgl/src/widgets/span \
vendor/lvgl/src/widgets/spinbox \
vendor/lvgl/src/widgets/spinner \
vendor/lvgl/src/widgets/switch \
vendor/lvgl/src/widgets/table \
vendor/lvgl/src/widgets/tabview \
vendor/lvgl/src/widgets/textarea \
vendor/lvgl/src/widgets/tileview \
vendor/lvgl/src/widgets/win \
vendor/lvgl/tests/makefile \
vendor/lvgl/tests/makefile_uefi \
vendor/lvgl/tests/src \
vendor/lvgl/tests/src/test_assets \
vendor/lvgl/tests/src/test_cases \
vendor/lvgl/tests/src/test_cases/cache \
vendor/lvgl/tests/src/test_cases/draw \
vendor/lvgl/tests/src/test_cases/libs \
vendor/lvgl/tests/src/test_cases/widgets \
vendor/lvgl/tests/src/test_libs/rnd_unicodes \
vendor/lvgl/tests/src/test_libs/rnd_unicodes/rnd_unicodes/src \
vendor/lvgl/tests/test_images/stride_align1/LZ4 \
vendor/lvgl/tests/test_images/stride_align1/RLE \
vendor/lvgl/tests/test_images/stride_align1/UNCOMPRESSED \
vendor/lvgl/tests/test_images/stride_align64/LZ4 \
vendor/lvgl/tests/test_images/stride_align64/RLE \
vendor/lvgl/tests/test_images/stride_align64/UNCOMPRESSED \
vendor/lvgl/tests/unity \
vendor/mesh \
vendor/tuong \
vendor/user_app \

